### ISSUE TITLE
Importing arduino library gave message error

### ISSUE THREAD

**Issue by yulrizka** [senseobservationsystems/commonsense-arduino-lib#1]
Step to repoduce:
1. installing the arduino IDE (mac version used)
2. Sketch > Import > Library
3. Choose "commonsense-arduino-lib-master.zip" downloaded from github

Result : 
![screenshot 2013-10-20 12 09 06](https://f.cloud.github.com/assets/117752/1367978/2faf291e-3970-11e3-9998-4aab8a37af15.png)

Extracting the zip file, rename it to commonsense and zip it again seems to be working. 

Maybe we should make this clear to user or provide useable download link to user.

/cc @epiccoolguy

**Comment by epiccoolguy** [comment]
Changed text to tell users to extract and rename the folder.
- SHA: e34ec04df00529ee35e43e4f6caf6a4995a15867
